Repository 2022-Harmony/NewsCommunity-bFinal, pull requests merged in 2022-07, with the labels that each got.

#58 프로필 페이지에서 자신이 쓴 댓글 모아보기
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentCreateRequestDto.java
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentEditRequestDto.java
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentResponseDto.java
  src/main/java/com/teamharmony/newscommunity/comments/entity/Comment.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/LikesRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
  src/main/java/com/teamharmony/newscommunity/comments/service/LikesService.java
Labels: feat

#77 프로필 사진 url 조회 기능 구현
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
Labels: feat, fix

#81 users패키지에서 인증, 인가 관련 부분 분리
  src/main/java/com/teamharmony/newscommunity/auth/config/security/AuthConstants.java
  src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
  src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/auth/entity/Tokens.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthorizationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/repository/TokensRepository.java
  src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
  src/main/java/com/teamharmony/newscommunity/auth/util/CookieUtil.java
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
  src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java
Labels: refactor, fix

#92 bookmark 도메인 정비 및 예외처리 시범 적용
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/bookmarks/controller/BookmarkController.java
  src/main/java/com/teamharmony/newscommunity/bookmarks/dto/RequestBookmarkDTO.java
  src/main/java/com/teamharmony/newscommunity/bookmarks/entity/Bookmarks.java
  src/main/java/com/teamharmony/newscommunity/bookmarks/repository/BookmarkRepository.java
  src/main/java/com/teamharmony/newscommunity/bookmarks/service/BookmarkService.java
  src/main/java/com/teamharmony/newscommunity/exception/Error.java
  src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
  src/main/java/com/teamharmony/newscommunity/exception/InvalidRequestException.java
Labels: feat

#97 접근 제한자 수정
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
Labels: fix

#98 예외처리 로직에 대한 필드값 수정 및 빌더 패턴 적용
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/exception/Error.java
  src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
Labels: refactor

#94 Fix: 댓글의 content column의 크기를 수정
  src/main/java/com/teamharmony/newscommunity/comments/entity/Comment.java
Labels: fix

#105 클래스 위치 변경
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
Labels: refactor

#107 쿠키 유효 시간 수정
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
Labels: fix

#127 Feat: 해당 에러에 대한 message와 stack trace를 log로 작성
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
Labels: feat

#128 Comment Entity column 크기 @Size 와 @Column(length = ) 중복 삭제
  src/main/java/com/teamharmony/newscommunity/comments/entity/Comment.java
Labels: fix

#131 Feat: logback 생성을 위한 xml 작성 및 Aop를 통한 parameter 로깅
  src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java
  src/main/resources/logback.xml
Labels: feat

#133 뉴스, 북마크 도메인에 대한 예외처리 적용 및 에러 객체 생성 방식 변경
  src/main/java/com/teamharmony/newscommunity/bookmarks/service/BookmarkService.java
  src/main/java/com/teamharmony/newscommunity/exception/InvalidRequestException.java
  src/main/java/com/teamharmony/newscommunity/news/service/NewsService.java
Labels: refactor

#141 로그아웃 후 로그인 시도 시 자동 재로그인되는 오류 수정
  src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
Labels: bug

#145 댓글 개수를 얻는 방식 수정
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: refactor

#144 배포문제 1차 해결
  .github/workflows/main.yml
  src/test/java/com/teamharmony/newscommunity/NewsCommunityApplicationTests.java
Labels: fix

#148 auth 패키지 예외 처리(필터 제외)
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
  src/main/java/com/teamharmony/newscommunity/auth/util/CookieUtil.java
  src/main/java/com/teamharmony/newscommunity/exception/TokenException.java
Labels: feat, fix

#152 뉴스 상세페이지 댓글 페이징 구현
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: feat

#155 회원 가입 시 ID 중복 체크를 위한 Dto 내부 클래스 생성
  src/main/java/com/teamharmony/newscommunity/users/dto/SignupRequestDto.java
Labels: enhancement

#158 모든 GET요청을 허용하고 비로그인 이용자 열람 및 기록을 위한 어노테이션 변경
  src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java
  src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
  src/main/java/com/teamharmony/newscommunity/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthorizationFilter.java
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/common/annotation/CurrentUser.java
  src/main/java/com/teamharmony/newscommunity/supports/controller/SupportController.java
  src/main/java/com/teamharmony/newscommunity/supports/service/SupportService.java
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
Labels: enhancement, fix

#159 프로필 페이지 댓글 페이징 기능
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: feat

#161 비로그인 상태에서 프로필 조회 불가한 오류
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
Labels: bug

#164 회원 가입 중복 체크되지 않는 오류 수정
  src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
Labels: bug

#167 좋아요 이력을 포함한 CommentResponseDto 반환
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentResponseDto.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: feat

#171 테스트 코드 관련 에러 수정
  src/test/java/com/teamharmony/newscommunity/news/controller/NewsControllerTest.java
  src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
Labels: fix

#173 토큰 갱신 관련 오류 수정 & 토큰 생성 비밀키 환경 변수 설정
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthorizationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/service/AuthService.java
  src/main/resources/application.properties
Labels: bug, fix

#175 s3 업로드시 public 권한으로 객체 생성
  src/main/java/com/teamharmony/newscommunity/users/filesotre/FileStore.java
  src/main/resources/application.properties
Labels: fix

#177 EB에 대한 CICD 구성
  .ebextensions/00-makeFiles.config
  .github/workflows/main.yml
  .platform/nginx/nginx.conf
  Procfile
  src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
  src/main/java/com/teamharmony/newscommunity/filter/SimpleCorsFilter.java
Labels: feat

#179 좋아요 이력 확인 오류
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: bug

#186 배포 브랜치를 main으로 변경
  .github/workflows/main.yml
Labels: feat

#189 상세페이지 댓글 페이징과 정렬 개선
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentResponseDto.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: bug, fix

#191 프로필 페이지 댓글 페이징 번호 개선
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: fix

#195 미비된 로깅 부분 보수
  src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
Labels: fix

#197 [Deploy] 2022-07-26 댓글 페이지 기능 개선, 로깅 미비 사항 개선 패치
  src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/dto/CommentResponseDto.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: feat

#194 기존 정렬 기능과 관련된 코드 삭제
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
Labels: refactor

#201 프로필 변경이 가능한 버킷으로 환경 변수 수정
  src/main/resources/application.properties
Labels: test

#203 [Deploy] 2022-07-26 리팩토링, s3 관련 환경 변수 변경
  src/main/java/com/teamharmony/newscommunity/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/comments/repository/CommentRepository.java
  src/main/java/com/teamharmony/newscommunity/comments/service/CommentService.java
  src/main/java/com/teamharmony/newscommunity/supports/service/SupportService.java
  src/main/resources/application.properties
Labels: deploy

#205 users, auth패키지 어노테이션 수정
  src/main/java/com/teamharmony/newscommunity/auth/entity/Tokens.java
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/users/dto/ProfileResponseDto.java
  src/main/java/com/teamharmony/newscommunity/users/dto/SignupRequestDto.java
  src/main/java/com/teamharmony/newscommunity/users/dto/UserResponseDto.java
  src/main/java/com/teamharmony/newscommunity/users/entity/Role.java
  src/main/java/com/teamharmony/newscommunity/users/entity/User.java
  src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java
  src/main/java/com/teamharmony/newscommunity/users/entity/UserRole.java
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
Labels: refactor

#212 로그인 Dto 적용
  src/main/java/com/teamharmony/newscommunity/auth/dto/SigninRequestDto.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/util/SigninValidator.java
Labels: enhancement, refactor

#209 좋아요 여부를 확인하는 과정 추가
  src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/comments/service/LikesService.java
Labels: enhancement

#215 프로필 업데이트 오류 해결
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
Labels: bug

#217 [Deploy] 2022-07-27 좋아요 기능 개선, 프로필 업데이트 오류 수정 패치
  src/main/java/com/teamharmony/newscommunity/auth/dto/SigninRequestDto.java
  src/main/java/com/teamharmony/newscommunity/auth/entity/Tokens.java
  src/main/java/com/teamharmony/newscommunity/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/auth/util/SigninValidator.java
  src/main/java/com/teamharmony/newscommunity/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/comments/service/LikesService.java
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/users/dto/ProfileResponseDto.java
  src/main/java/com/teamharmony/newscommunity/users/dto/SignupRequestDto.java
  src/main/java/com/teamharmony/newscommunity/users/dto/UserResponseDto.java
  src/main/java/com/teamharmony/newscommunity/users/entity/Role.java
  src/main/java/com/teamharmony/newscommunity/users/entity/User.java
  src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java
  src/main/java/com/teamharmony/newscommunity/users/entity/UserRole.java
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
Labels: deploy

#219 스웨거 적용 위한 디펜던시 추가
  build.gradle
Labels: feat

#222 프로필 RequestDto 적용
  src/main/java/com/teamharmony/newscommunity/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/users/dto/ProfileRequestDto.java
  src/main/java/com/teamharmony/newscommunity/users/entity/UserProfile.java
  src/main/java/com/teamharmony/newscommunity/users/service/UserService.java
  src/main/java/com/teamharmony/newscommunity/users/vo/ProfileVO.java
Labels: fix

#223 Fix: XSS 필터 적용 #213
  build.gradle
  src/main/java/com/teamharmony/newscommunity/config/WebMvcConfig.java
  src/main/java/com/teamharmony/newscommunity/util/HTMLCharacterEscapes.java
Labels: feat

#227 스웨거 세팅 다시 시도
  build.gradle
  src/main/java/com/teamharmony/newscommunity/auth/config/security/SecurityConfig.java
  src/main/java/com/teamharmony/newscommunity/config/SwaggerConfig.java
  src/main/resources/application.properties
Labels: bug

#234 프로젝트 패키지 구조 변경 3
  src/main/java/com/teamharmony/newscommunity/common/ApiResponse.java
  src/main/java/com/teamharmony/newscommunity/common/ApiResponseHeader.java
  src/main/java/com/teamharmony/newscommunity/config/WebMvcConfig.java
  src/main/java/com/teamharmony/newscommunity/util/HTMLCharacterEscapes.java
Labels: rename

#238 예외 처리 관련 수정
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/exception/Error.java
  src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
Labels: enhancement, fix

#237 comment swagger 적용
  src/main/java/com/teamharmony/newscommunity/config/SwaggerConfig.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentCreateRequestDto.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentEditRequestDto.java
Labels: feat

#241 인증, 인가 필터 예외 처리
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/config/security/SecurityConfig.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/filter/CustomAuthorizationFilter.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/filter/ExceptionHandlerFilter.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/service/AuthService.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/util/CookieUtil.java
  src/main/java/com/teamharmony/newscommunity/exception/AuthException.java
  src/main/java/com/teamharmony/newscommunity/exception/TokenException.java
Labels: enhancement, fix, rename

#244 예외 객체 생성 방식 변경
  src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
Labels: refactor

#243 Comment 패키지 JavaDoc 추가
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/service/CommentService.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/service/LikesService.java
Labels: comment

#246 UserService에서 Profile image 관련 함수를 util로 분리
  src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
  src/main/java/com/teamharmony/newscommunity/domain/users/util/ProfileUtil.java
Labels: refactor

#249 뉴스 도메인과 북마크 도메인에 javadoc, swagger 적용 및 미비 부분 리팩토링
  src/main/java/com/teamharmony/newscommunity/common/util/TimestampedOnLog.java
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/controller/BookmarkController.java
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/dto/BookmarkRequestDto.java
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/dto/BookmarkResponseDto.java
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/service/BookmarkService.java
  src/main/java/com/teamharmony/newscommunity/domain/news/controller/NewsController.java
  src/main/java/com/teamharmony/newscommunity/domain/news/dto/CreateNewsAccessLogRequestDto.java
  src/main/java/com/teamharmony/newscommunity/domain/news/dto/NewsDetailResponseDto.java
  src/main/java/com/teamharmony/newscommunity/domain/news/dto/NewsResponseDto.java
  src/main/java/com/teamharmony/newscommunity/domain/news/entity/NewsAccessLog.java
  src/main/java/com/teamharmony/newscommunity/domain/news/service/NewsService.java
Labels: refactor

#251 250/refactor exception logic apply javadoc
  src/main/java/com/teamharmony/newscommunity/aop/ParameterAop.java
  src/main/java/com/teamharmony/newscommunity/aop/advice/GlobalHandlerException.java
  src/main/java/com/teamharmony/newscommunity/exception/Error.java
  src/main/java/com/teamharmony/newscommunity/exception/ErrorResponse.java
  src/main/java/com/teamharmony/newscommunity/exception/InvalidRequestException.java
Labels: refactor

#258 전반적인 코드 리팩토링
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentCreateRequestDto.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentEditRequestDto.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/service/CommentService.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/service/LikesService.java
Labels: refactor, comment

#248 users package 일부분 변경
  src/main/java/com/teamharmony/newscommunity/domain/users/controller/UserController.java
  src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
Labels: refactor, fix, comment

#259 버킷 설정 변경
  src/main/java/com/teamharmony/newscommunity/config/AmazonConfig.java
  src/main/resources/application.properties
Labels: fix

#260 uuid를 pk로 사용하는 도메인에 인덱싱
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/entity/Bookmarks.java
  src/main/java/com/teamharmony/newscommunity/domain/news/entity/NewsAccessLog.java
  src/main/java/com/teamharmony/newscommunity/domain/news/entity/NewsTable.java
  src/test/java/com/teamharmony/newscommunity/news/service/NewsServiceTest.java
Labels: feat

#261 auth 패키지 일부분 변경
  src/main/java/com/teamharmony/newscommunity/domain/auth/controller/AuthController.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/service/AuthService.java
  src/main/java/com/teamharmony/newscommunity/domain/auth/util/CookieUtil.java
Labels: refactor, comment

#267 예외 처리 변경
  src/main/java/com/teamharmony/newscommunity/domain/auth/filter/CustomAuthorizationFilter.java
  src/main/java/com/teamharmony/newscommunity/domain/users/entity/User.java
  src/main/java/com/teamharmony/newscommunity/domain/users/service/UserService.java
Labels: refactor, fix
