Repository 2022-Harmony/NewsCommunity-bFinal, pull requests merged in 2022-08, with the labels that each got.

#274 news, bookmarks, comments 패키지 스웨거 보완
  src/main/java/com/teamharmony/newscommunity/domain/bookmarks/controller/BookmarkController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/CommentController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/controller/LikesController.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/dto/CommentResponseDto.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/service/CommentService.java
  src/main/java/com/teamharmony/newscommunity/domain/news/controller/NewsController.java
Labels: enhancement

#279 @ManyToOne 쓰는 Entity FetchType.LAZY로 수정
  src/main/java/com/teamharmony/newscommunity/domain/comments/entity/Comment.java
  src/main/java/com/teamharmony/newscommunity/domain/comments/entity/Likes.java
  src/main/java/com/teamharmony/newscommunity/domain/supports/entity/Support.java
  src/main/java/com/teamharmony/newscommunity/domain/users/entity/UserRole.java
Labels: refactor

#281 Fix: application.properties에서 DB를 RDS 주소에서 로컬 주소로 변경
  src/main/resources/application.properties
Labels: fix
